CREATE DATABASE IF NOT EXISTS SCRIPT_RELACIONAMENTOS;

USE SCRIPT_RELACIONAMENTOS.sql

CREATE TABLE CLENTES (
    ID_CLENTES INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CLIENTE VARCHAR(100) NOT NULL
);


CREATE TABLE PEDIDOS (
    ID PEDIDOS INT AUTO INCREMENT KEY,
    ID_CLIENTE INT NOT NULL,
    DATA_PEDIDO DATE NOT NULL,
    VALOR_TOTAL DECIMAL(10,2) NOT NULL,
    Foreign Key (id_clientes) REFERENCES clientes(id_Clientes)
);

CREATE TABLE ESTOQUE (
    ID_ESTOQUE INT AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUTO INT NOT NULL UNIQUE,
    QUANTIDADE INT NOT NULL,
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);

CREATE TABLE PRODUTOS (
    ID_PRODUTO INT INCREMENT PRIMARY KEY,
    NOME_PRODUTO VARCHAR(100) NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL
);

SELECT * FROM ESTOQUE;

SELECT * FROM PRODUTO;

INSERT INTO PRODUTOS (NOME_PRODUTO, PRECO) VALUES
('PRODUTO A', 10.00);
('PRODUTO B', 20.00);
('PRODUTO C', 30.00);
