CREATE DATABASE CASTELLO

CREATE TABLE ALUNOS (
    ID_ALUNO BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR (100) NOT NULL,
    CPF CHAR (14) NOT  NULL UNIQUE,
    STATUS_ALUNO ENUM('ATIVO', 'INATIVO', 'CONCLUIDO') DEFAULT 'ATIVO',
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

-- VISUALIZAR TODOS OS BD
SHOW SCHEMAS;

-- VISUALIZAR AS TABELAS DO BD
SHOW TABLES;

-- DESCRIÇÃO DE ATRIBUTOS DA TABELAS ALUNOS
DESCRIBE ALUNOS;

-- DELETAR BANCO DE DADOS
DROP DATABASE CASTELLO;

-- DELETAR TABELAS
DROP TABLES ALUNOS;